SimpleWebApp/Models/ErrorViewModel.cs
namespace SimpleWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SimpleWebApp/Models/Person.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SimpleWebApp.Models
{
    public class Person
    {
        [Key]
        public int Id { get; set; }

        [Required (ErrorMessage = "Name is required.")]
        public string Name { get; set; }
        [Range(0,999)]
        public string Age { get; set; }
        [DisplayName("Birth Date")]
        public DateOnly BirthDate { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    }
}

SimpleWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;//import namespace necessesary classes for creating controllers
using SimpleWebApp.Models;//import model
using System.Diagnostics;//for system diagnostics and debugging

//This controller handles requests related to the home page 
//    and other general pages of the application.

namespace SimpleWebApp.Controllers
{
    public class HomeController : Controller 
    {
        private readonly ILogger<HomeController> _logger;//constructor of the controller

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index() //action method that handles requests to the root URL
        {
            return View(); //return index page
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SimpleWebApp/Controllers/PersonInfoController.cs
using Microsoft.AspNetCore.Mvc;
using SimpleWebApp.Data;
using SimpleWebApp.Migrations;
using SimpleWebApp.Models;
using System.ComponentModel; //data binding with models

namespace SimpleWebApp.Controllers 
{
    public class PersonInfoController : Controller //define action method inside this class
    {
        private readonly ApplicationDbContext _db;
        //declare a variable for providing access to interact with database
        public PersonInfoController(ApplicationDbContext db)
        {
            _db = db; //store the object from this contructor 
        }

        public IActionResult Index()
        {
            List<Person> objPersonList = _db.Person_Info.ToList();
            //convert the object from the data base to list and store it

            return View(objPersonList);
        }

        public IActionResult Create()
        {
            return View();    
        }
        [HttpPost] //this specifies that this action handles HTTP POST
        public IActionResult Create(Person obj) //take a parameter from Model Person
        //The model binding system automatically maps the form submitted
        //in the create view to Person
        {
            if (ModelState.IsValid)
            {
                _db.Person_Info.Add(obj); //add a new obj to database
                _db.SaveChanges();
                TempData["success"] = "Create successfully"; //inside TempData will stay for one instance
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Edit(int? id)
        {
            if(id==null || id ==0)
            {
                return NotFound();
            }
            Person? personFromDb = _db.Person_Info.FirstOrDefault(x => x.Id == id);
            if(personFromDb == null)
            {
                return NotFound();
            }

            return View(personFromDb);
        }
        [HttpPost]
        public IActionResult Edit(Person obj)
        {
            if (ModelState.IsValid)
            {
                _db.Person_Info.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Edited successfully";
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Delete(int? id) //delete get method
            //? makes the parameter nullable
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Person? personFromDb = _db.Person_Info.FirstOrDefault(x => x.Id == id);
            
            if (personFromDb == null)
            {
                return NotFound();
            }

            return View(personFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            Person? obj = _db.Person_Info.FirstOrDefault(x => x.Id == id);
            if (obj == null)
            { 
                return NotFound();
            }
            _db.Person_Info.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Deleted successfully";
            return RedirectToAction("Index");
            }
        }
}

SimpleWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>You can view person info on the top menu.</p>
</div>

SimpleWebApp/Views/PersonInfo/Create.cshtml
@model Person //for direct access to a model

<form method="post">
    <div class="card border-dark p-3 mt-4" style="max-width: 40rem; margin: auto">
        <div class="card-header text-light"> 
            <h1>Enter Person Data</h1>
         </div>
        <div>
            <label asp-for="Name" class="form-label mt-2"></label> 
            @* asp-for is used to bind input fields to match in a model class *@
            <input asp-for="Name" class="form-control" placeholder="Enter Name">
            <span asp-validation-for="Name" class="text-danger"></span>
            @* this is a ASP.NET Core's built in validation system *@
        </div>
        <div>
            <label asp-for="Age" class="form-label mt-4"></label>
            <input asp-for="Age" class="form-control" placeholder="Age">
            <span asp-validation-for="Age" class="text-danger"></span>

        </div>
        <div>
            <label asp-for="BirthDate" class="form-label mt-4"></label>
            <input type="Date" asp-for="BirthDate" class="form-control" placeholder="Enter Birth Date">
            <span asp-validation-for="BirthDate" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Address" class="form-label mt-4"></label>
            <input asp-for="Address" class="form-control" placeholder="Enter Address">
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Phone" class="form-label mt-4"></label>
            <input asp-for="Phone" class="form-control" placeholder="Enter Phone Number">
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>

        <div class="btn-group mt-4">
            <div>
                <button type="submit" class="btn btn-lg btn-outline-secondary">Submit</button>
            </div>
            <div>
                <a asp-controller="PersonInfo" asp-action="Index" class="btn btn-lg btn-outline-secondary"> BACK</a>
            </div>
        </div>
    </div>
</form>

SimpleWebApp/Views/PersonInfo/Delete.cshtml
@model Person

<form method="post">
    <div class="card border-dark p-3 mt-4" style="max-width: 40rem; margin: auto">
        <div class="card-header text-light">
            <h1>Delete Data for @Model.Name</h1>
        </div>
        <div>
            <label asp-for="Name" class="form-label mt-2"></label>
            <input asp-for="Name" disabled class="form-control" placeholder="Enter Name">
        </div>
        <div>
            <label asp-for="Age" class="form-label mt-4"></label>
            <input asp-for="Age" disabled class="form-control" placeholder="Age">

        </div>
        <div>
            <label asp-for="BirthDate" class="form-label mt-4"></label>
            <input type="Date" asp-for="BirthDate" disabled class="form-control" placeholder="Enter Birth Date">
        </div>
        <div>
            <label asp-for="Address" class="form-label mt-4"></label>
            <input asp-for="Address" disabled class="form-control" placeholder="Enter Address">
        </div>
        <div>
            <label asp-for="Phone" class="form-label mt-4"></label>
            <input asp-for="Phone" disabled class="form-control" placeholder="Enter Phone Number">
        </div>

        <div class="btn-group mt-4">
            <div>
                <button type="DELETE" class="btn btn-lg btn-outline-danger">DELETE</button>
            </div>
            <div>
                <a asp-controller="PersonInfo" asp-action="Index" class="btn btn-lg btn-outline-secondary"> BACK</a>
            </div>
        </div>
    </div>
</form>

SimpleWebApp/Views/PersonInfo/Edit.cshtml
@model Person

<form method="post">
    <div class="card border-dark p-3 mt-4" style="max-width: 40rem; margin: auto">
        <div class="card-header text-light">
            <h1>Edit Data for @Model.Name</h1>
        </div>
        <div>
            <label asp-for="Name" class="form-label mt-2"></label>
            <input asp-for="Name" class="form-control" placeholder="Enter Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Age" class="form-label mt-4"></label>
            <input asp-for="Age" class="form-control" placeholder="Age">
            <span asp-validation-for="Age" class="text-danger"></span>

        </div>
        <div>
            <label asp-for="BirthDate" class="form-label mt-4"></label>
            <input type="Date" asp-for="BirthDate" class="form-control" placeholder="Enter Birth Date">
            <span asp-validation-for="BirthDate" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Address" class="form-label mt-4"></label>
            <input asp-for="Address" class="form-control" placeholder="Enter Address">
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Phone" class="form-label mt-4"></label>
            <input asp-for="Phone" class="form-control" placeholder="Enter Phone Number">
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>

        <div class="btn-group mt-4">
            <div>
                <button type="submit" class="btn btn-lg btn-outline-secondary">UPDATE</button>
            </div>
            <div>
                <a asp-controller="PersonInfo" asp-action="Index" class="btn btn-lg btn-outline-secondary"> BACK</a>
                @* specify the controller and action you want to go *@
            </div>
        </div>
    </div>
</form>

SimpleWebApp/Views/PersonInfo/Index.cshtml
@model List<Person>

<div class="row mx-5">
    <div class="d-flex justify-content-between">
        <h1>
            Person List
        </h1>
        <div class="pt-1 align-middle">
        <a asp-controller="PersonInfo" asp-action="Create" class="btn btn-outline-light">
            CREATE
        </a>
        </div>
     </div>
</div>
<table class="table table-hover table-striped mt-3">
    <thead>
    <tr class="table-secondary">
        <th scope="row">Name</th>
        <th>Age</th>
        <th>Birth Date</th>
        <th>Address</th>
        <th>Phone</th>
        <th class="text-center px-0">Options</th>
    </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
             <tr class = "table-primary align-middle">
                <td>@obj.Name</td>
                <td>@obj.Age</td>
                <td>@obj.BirthDate</td>
                <td>@obj.Address</td>
                <td>@obj.Phone</td>
                <td class="table-light text-center px-0">
                    <a asp-controller="PersonInfo" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-warning">
                            <i class="bi bi-pencil-fill"></i>
                        </a>
                    <a asp-controller="PersonInfo" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger">
                            <i class="bi bi-trash-fill"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>

SimpleWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SimpleWebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-expand-lg bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SimpleWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="PersonInfo" asp-action="Index">Person Info</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" /> @* import a reusable piece of HTML page *@
            @RenderBody() @* view html pages will appear in this section *@
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted">
        <div class="container">
            &copy; 2024 - SimpleWebApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SimpleWebApp/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": false,
            "progressBar": true,
            "positionClass": "toast-top-center",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        toastr.success('@TempData["success"]')
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["error"]')
    </script>
}